% Define source (s) and target (t) node pairs based on the flowchart connections
s = {'K', 'M', 'O', 'A', 'O', 'H', 'Q', 'B', 'RR', ...
     'Q', 'E', 'I', 'E', 'B', 'Q', 'B', 'R', 'C', 'D', ...
     'D', 'D', 'D', 'G', 'J', 'L'};

t = {'O', 'K', 'A', 'B', 'H', 'E', 'RR', 'RR', 'E', ...
     'I', 'I', 'D', 'J', 'C', 'R', 'R', 'D', 'D', 'F', ...
     'G', 'K', 'N', 'L', 'L', 'K'};

% Create the directed graph object
G = digraph(s, t);

% Define unique node IDs and their matching descriptive labels
nodeIDs = {'P', 'M', 'K', 'O', 'A', 'B', 'H', 'E', 'Q', 'RR', ...
           'I', 'J', 'C', 'R', 'D', 'F', 'G', 'N', 'L'};

nodeLabels = {'Demi Water', 'Feedwater Tank', 'Deaerator', 'Boiler Feedwater', ...
              'Boiler-14', '50 bar header', 'Boiler-15', '20 bar header', ...
              'Spray Water', 'PRV (20 bar)', 'Steam drum', 'Med pressure users', ...
              'Turbine', 'PRV (2.5 bar)', '2.5 bar header', 'City heating', ...
              'Low pressure users', 'PRV vent & sootblower', 'Condensate tank'};

% Map and assign the descriptive labels to the graph nodes
[~, idx] = ismember(G.Nodes.Name, nodeIDs);
G.Nodes.Label = nodeLabels(idx)';

% --- Visualization Configuration ---
figure('Name', 'Steam & Water Utility Network', 'Color', 'w');

% Plot using a top-down layered layout to mimic the 'flowchart TD' structure
h = plot(G, 'NodeLabel', G.Nodes.Label, ...
            'Layout', 'layered', ...
            'Direction', 'down', ...
            'Marker', 's', ...
            'MarkerSize', 8, ...
            'NodeColor', [0 0.4470 0.7410], ...
            'EdgeColor', [0.5 0.5 0.5], ...
            'LineWidth', 1.5);

title('Water and Steam Utility Flow Network', 'FontSize', 14);
axis off;

